
Status: FAILED!
Check: 1
Test: The program can be executed several times to ensuring the random number changes.
Reason: Unable to find '[" That's correct!"]' in the program's output.
Please insert a number between 1-10: Invalid input. Please enter a valid integer between 1 and 10.
Please insert a number between 1-10: The result was 2. Your guess was NOT correct. Try again.
Please insert a number between 1-10: Invalid input. Please enter a valid integer between 1 and 10.
Please insert a number between 1-10: The result was 2. Your guess was correct, congratulations!
.
Error : AssertionError - Unable to find  That's correct! in the program's output.
Timestamp: 2024-10-16 16:43:08.518504

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:08.626095

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:08.626187

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:08.746385

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:08.746481

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:08.828398

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:08.828469

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:08.912682

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:08.912753

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:08.996248

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:08.996320

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:09.106476

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:09.106561

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:09.188900

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:09.188973

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:09.279742

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:09.279840

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:09.377576

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:09.377646

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:09.460497

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:09.460567

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:09.543805

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:09.543868

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:09.653850

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:09.653919

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:09.756529

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:09.756599

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:09.865795

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:09.865884

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:09.962428

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:09.962517

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:10.064526

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:10.064595

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:10.145224

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:10.145288

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:10.255190

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:10.255265

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:10.363511

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:10.363593

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:10.445594

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:10.445661

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:10.528382

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:10.528454

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:10.610097

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:10.610170

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:10.691192

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:10.691256

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:10.772056

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:10.772122

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:10.852818

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:10.852883

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:10.934441

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:10.934512

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.016129

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.016200

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.097704

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.097773

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.178741

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.178810

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.259796

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.259866

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.342180

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.342249

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.423552

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.423617

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.506028

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.506104

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.587131

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.587196

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.668088

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.668152

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.749331

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.749392

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.830164

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.830237

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.911542

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.911617

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.991800

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:11.991862

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:12.073250

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:12.073316

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:12.155351

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:12.155421

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:12.236873

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:12.236940

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:12.317737

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:12.317802

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:12.399066

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:12.399163

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:12.481852

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:12.481932

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:12.563152

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:12.563219

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:12.643091

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:12.643186

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:12.723706

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:12.723768

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:12.803969

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:12.804029

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:12.885122

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:12.885187

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:12.966780

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:12.966846

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:13.047924

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:13.048192

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:13.128791

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:13.128855

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:13.236612

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:13.236679

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:13.317054

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:13.317115

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:13.398782

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:13.398852

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:13.480193

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:13.480258

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:13.561535

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:13.561602

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:13.642266

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:13.642331

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:13.723964

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:13.724032

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:13.831057

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:13.831150

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:13.912750

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:13.912818

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:14.020209

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:14.020273

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:14.128278

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:14.128349

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:14.210207

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:14.210283

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:14.291388

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:14.291466

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:14.372758

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:14.372826

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:14.453620

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:14.453685

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:14.535206

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:14.535273

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:14.616333

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:14.616402

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:14.697572

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:14.697648

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:14.778762

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:14.778828

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:14.859588

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:14.859660

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:14.941196

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:14.941265

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:15.022516

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:15.022583

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:15.103362

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:15.103431

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:15.185089

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:15.185162

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:15.266072

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:15.266139

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:15.346822

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:15.346889

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:15.454956

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:15.455027

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:15.537939

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:15.538006

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:15.619624

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:15.619692

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:15.701037

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:15.701105

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:15.782404

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:15.782470

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:15.864008

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:15.864096

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:15.945794

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:15.945862

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:16.027065

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:16.027159

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:16.109445

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:16.109515

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:16.190550

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:16.190617

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:16.272376

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:16.272452

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:16.353422

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:16.353493

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:16.434656

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:16.434723

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:16.516612

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:16.516681

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:16.598052

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:16.598118

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:16.680165

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:16.680235

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:16.762077

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:16.762148

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:16.870177

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:16.870250

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:16.951223

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:16.951288

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:17.032919

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:17.032988

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:17.114174

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:17.114240

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:17.196019

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:17.196091

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:17.278377

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:17.278445

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:17.360007

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:17.360085

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:17.443043

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:17.443160

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:17.526070

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 16, in <module>
    number_in = int(input("Please insert a number between 1-10: "))
EOFError: EOF when reading a line

Timestamp: 2024-10-16 16:43:17.526156

Status: FAILED!
Check: 3
Test: The program generates a different random number for each run.
Reason: The correct number does not appear to be random.
Error : AssertionError - 
Timestamp: 2024-10-16 16:43:17.552958
